name: yuunagi
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  get: ^4.6.5
  auto_route: ^7.8.0
  jm_dict: ^0.2.0
  kanji_dictionary: ^1.0.5+1
  flutter:
    sdk: flutter
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/raw/JMdict_e_examp.gz

